# this file is HEAVILY influenced by https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.travis.yml

sudo: false
dist: trusty
language: c++

cache: ccache

notifications:
  email: false

env:
  global:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  # "Defining the build matrix only with matrix.include leads to an additional, unwanted job"
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  # these apt sources will be referenced later (by using *name)
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

compiler: gcc
os: linux

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    # GCC 4.8
    - env: COMPILER=g++-4.8 BUILD_TYPE=Debug CPP=11 CODE_COVERAGE=true
      compiler: gcc
      addons: &gcc48
        apt:
          packages: ["g++-4.8", "g++-4.8-multilib", "libc6-dbg", "libc6-dbg:i386", "lcov", "astyle", "valgrind"]
          sources: *apt_sources

    # GCC 6
    - env: COMPILER=g++-6 BUILD_TYPE=Debug CPP=11
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ["g++-6", "g++-6-multilib", "libc6-dbg", "libc6-dbg:i386", "lcov", "astyle", "valgrind"]
          sources: *apt_sources

# Install dependencies
before_install:
  - pip install --user cpp-coveralls          

before_script:
  - if [ -n "${CLANG}" ]; then COMPILER="$CLANG"; fi
  - ${COMPILER} --version
  - CXX="$COMPILER"

script:
  - make all
  - valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes --trace-children=yes ./Bench/bin/main

after_success:
  - if [ -n "${CODE_COVERAGE}" ]; then coveralls -b ./Bench/obj -i ./Bench/src --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'; fi
  - if [ -n "${CODE_COVERAGE}" ]; then bash <(curl -s https://codecov.io/bash); fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "sauvik3"
  - git config --local user.email "sauvik3@gmail.com"
  - git remote add origin https://user:${GH_TOKEN}@github.com/user/repo.git
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  api_key:
    secure: XFDGSQMDMujr04zdv0i41HQqVDWX4R0HqohnWj8mZe4pwixOl/6dQd+O6rnguwmCoD6uzbxSptdHKXMi33Wp+izYG1J+Kne5aFVnlTJPt+YFmSgNd2kwmKzgFWNHAZ+iqPyR/6TPAWmGE0eWAS9n/aJPt5FY4f++FtpABRn6ybx+nHiH8pN19nn4vdkx3B71o9SVfL4h1fz5GPpe6yTjfg1lNMyjxAtWSEB+pms+zGWqG6njWgzYuMGj7EllDhA+9FenAf8yJeP54b+Ub3igtVuWHo/IcsHv3++Dq94qtV14VvlCkGH+phmvqE2dg+3R/uEKGMKcXhjbiwb3B53AaovS3ixF8vBVUIGV9N3efPN/CKFmahN3EMHtVy3hpPtpiZ3KiP3b50QKAORgKeR/tVoUrTmUayqk4kzHN3fTAfFUj6YLWFmpa/gQOv9PYyNm4Ld9dZItJxbgGxQQvhk6A9QqFQROL0NMWbee9icvdizsHu5O1tpDiz8rq0nxpQgvjDNO3oLNdwUx2REYt2Z8U8nx/bt76+hwvZYOlaoruyYJhNIeLDh9S7mHvNfZyL+rt0Awj0WfGjWLylUNxMbT7XMOe8//8k7Veg5oWN6Dt7QiFIWWjXOc3VXx7fplVh6dL2GWMCcka9tpfol2aDY6klR+B+hSverO+MIDdI5+Vp8=
  provider: releases
  file:
    - "./Main/bin/main"
    - "./Matrix/bin/matrix"
  skip_cleanup: true
