# this file is HEAVILY influenced by https://github.com/CleverRaven/Cataclysm-DDA/blob/master/.travis.yml

sudo: false
dist: trusty
language: c++

cache: ccache

notifications:
  email: false

env:
  global:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  # "Defining the build matrix only with matrix.include leads to an additional, unwanted job"
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  # these apt sources will be referenced later (by using *name)
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

compiler: gcc
os: linux

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    # GCC 4.8
    - env: COMPILER=g++-4.8 BUILD_TYPE=Debug CPP=11 CODE_COVERAGE=true
      compiler: gcc
      addons: &gcc48
        apt:
          packages: ["g++-4.8", "g++-4.8-multilib", "libc6-dbg", "libc6-dbg:i386", "lcov", "astyle", "valgrind"]
          sources: *apt_sources

    # GCC 6
    - env: COMPILER=g++-6 BUILD_TYPE=Debug CPP=11
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ["g++-6", "g++-6-multilib", "libc6-dbg", "libc6-dbg:i386", "lcov", "astyle", "valgrind"]
          sources: *apt_sources

# Install dependencies
before_install:
  - pip install --user cpp-coveralls          

before_script:
  - if [ -n "${CLANG}" ]; then COMPILER="$CLANG"; fi
  - ${COMPILER} --version
  - CXX="$COMPILER"

script:
  - make all
  - valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes --trace-children=yes ./Bench/bin/main

after_success:
  - if [ -n "${CODE_COVERAGE}" ]; then coveralls -r . -b obj --gcov /usr/bin/gcov-4.8; fi
  - if [ -n "${CODE_COVERAGE}" ]; then bash <(curl -s https://codecov.io/bash); fi
